name: Run Corellium MATRIX solution

on: [push]

jobs:

  ios:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: corellium/matrix
          path: main
          ref: core-7866-open-app

      - name: Run Corellium MATRIX
        uses: corellium/matrix@core-7866-open-app
        env:
          PROJECT: ${{ secrets.CORELLIUM_PROJECT_ID }}
          API_TOKEN: ${{ secrets.CORELLIUM_API_KEY }}
        with:
          deviceFlavor: 'iphone14p'
          deviceOS: '17.2'
          server: 'https://jedi.enterprise.corellium.com'
          appPath: './apps/Corellium_Cafe.ipa'
          userActions: './inputs.json'
          keywords: './keywords.txt'

  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: corellium/matrix
          path: main
          ref: core-7866-open-app

      - name: Run Corellium MATRIX
        uses: corellium/matrix@core-7866-open-app
        env:
          PROJECT: ${{ secrets.CORELLIUM_PROJECT_ID }}
          API_TOKEN: ${{ secrets.CORELLIUM_API_KEY }}
        with:
          deviceFlavor: 'ranchu'
          deviceOS: '14.0.0'
          server: 'https://jedi.enterprise.corellium.com'
          appPath: './apps/Corellium_Cafe.apk'
          userActions: './inputs.json'
          keywords: './keywords.txt'
