name: Run Corellium MATRIX solution

on: [push]

jobs:
  corellium-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Corellium MATRIX
        id: corellium-matrix
        uses: corellium/matrix@core-7413
        env:
          PROJECT: ${{ secrets.CORELLIUM_PROJECT_ID }}
          API_TOKEN: ${{ secrets.CORELLIUM_API_KEY }}
        with:
          deviceFlavor: 'iphone14p'
          deviceOS: '17.2'
          server: 'https://jedi.enterprise.corellium.com'
          appPath: 'https://www.dropbox.com/scl/fi/a5wodpmpbrsn8nxtm1uof/Corellium_Cafe.ipa?rlkey=do4aqp1gbd6vuljjkhf71ois9&st=p36wn82o&dl=1'
          userActions: 'https://drive.usercontent.google.com/download?id=11lrp46uk_1HRupp23t5de3fZ1ueH8C6w'
          keywords: 'https://drive.usercontent.google.com/download?id=1E2dQY9llh4cotntPz2ms_qTN71_qQR2I'

      - run: echo "${{ steps.corellium-matrix.outputs.report }}"
